"""add_badges_to_rngdle

Revision ID: c818d80153fa
Revises: af8e3b2c1d5f
Create Date: 2026-08-04 18:20:03.233864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c818d80153fa"
down_revision: Union[str, Sequence[str], None] = "af8e3b2c1d5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rngdle", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("badge_count", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rngdle", schema=None) as batch_op:
        batch_op.drop_column("badge_count")

    # ### end Alembic commands ###
